# fly.toml file generated for udemycourse on 2023-03-22T13:20:11+01:00

app = "udemycourse"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"

[experimental]
  auto_rollback = true

[build]
  image = "jonahcarneskog/udemycourse:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  StripeSettings__PublishableKey = "pk_test_51Mo1JNHg5sd7HO3LvTn5ZLTCmiAa7aPARGNTrOkH0dmLLoxCo9HbJB7y7pyY9L87NUdKOY1Y5XQE7BujEaAkjcF000yFvknLRj"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
